const accounts={
  '主账户':{name:'主账户',funds:[
    {name:'国泰半导体设备ETF联接C',code:'019633',category:'基金',amount:10000,today:-.015,hold:.052,history:[.02,.06,.04,.12,.1,.15,.2,.18,.23,.31,.28,.34],holdings:[['兆易创新','8.31%'],['北方华创','7.86%'],['中微公司','6.42%']],transactions:[['2026-07-13','买入','¥10,000']]},
    {name:'华夏黄金ETF联接C',code:'008702',category:'基金',amount:15000,today:.008,hold:.124,history:[.04,.06,.03,.08,.12,.1,.15,.18,.22,.2,.24,.29],holdings:[['黄金现货','92.40%'],['现金及其他','7.60%']],transactions:[['2026-07-05','买入','¥15,000']]}
  ]}
};
let active='主账户',view='overview',filter='全部';const root=document.querySelector('#view-root'),title=document.querySelector('#page-title');const money=n=>`¥${Math.round(n).toLocaleString('zh-CN')}`,pct=n=>`${n>=0?'+':''}${(n*100).toFixed(2)}%`,acct=()=>accounts[active]||{name:active||'无账户',funds:[]},total=()=>acct().funds.reduce((s,f)=>s+f.amount,0),daily=()=>acct().funds.reduce((s,f)=>s+f.amount*f.today,0);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function row(f){const d=f.amount*f.today;return `<button class="fund-row" data-code="${f.code}"><div class="fund-info"><b>${esc(f.name)}</b><small>${f.code} · ${f.category}</small></div><div class="fund-est"><strong class="${f.hold<0?'negative':'positive'}">${money(f.amount*f.hold)}</strong><span>${pct(f.hold)}</span></div><div class="fund-today"><strong class="${d<0?'negative':'positive'}">${money(d)}</strong><span>${pct(f.today)}</span></div><div class="fund-amount">${money(f.amount)}</div><span class="row-chevron">›</span></button>`}
function overview(){title.textContent='今天，先看组合。';const t=total(),d=daily();root.innerHTML=`<div class="kpis"><div class="kpi"><span class="kpi-label">当前账户总资产</span><strong class="kpi-value">${money(t)}</strong><span class="kpi-sub">${active}</span></div><div class="kpi"><span class="kpi-label">今日估算收益</span><strong class="kpi-value ${d<0?'negative':'positive'}">${money(d)}</strong><span class="kpi-sub ${d<0?'negative':'positive'}">今日 ${t?pct(d/t):'+0.00%'}</span></div><div class="kpi"><span class="kpi-label">累计收益</span><strong class="kpi-value negative">−¥9,839</strong><span class="kpi-sub">计划周期 · 1 年</span></div></div><section class="list-section account-section"><div class="section-head"><div><p class="eyebrow">账户管理</p><h2>选择账户</h2></div><button class="primary" data-action="add-account">新增账户</button></div><div class="account-list">${Object.values(accounts).map(a=>{const at=a.funds.reduce((s,f)=>s+f.amount,0),ad=a.funds.reduce((s,f)=>s+f.amount*f.today,0);return `<button class="account-card" data-account="${esc(a.name)}"><div><b>${esc(a.name)}</b><small>${a.funds.length?a.funds.length+' 项持仓':'暂无持仓'}</small></div><div><strong>${money(at)}</strong><span class="${ad<0?'negative':'positive'}">${money(ad)} 今日</span></div><span class="row-chevron">›</span></button>`}).join('')}</div></section>`}
function portfolio(){title.textContent=active;const list=acct().funds.filter(f=>filter==='全部'||f.category===filter);root.innerHTML=`<section class="list-section"><div class="section-head"><div><p class="eyebrow">持仓 / ${acct().funds.length} 项</p><h2>持仓列表</h2></div><button class="primary" data-action="add-fund">增加基金</button></div><div class="category-tabs" role="tablist">${['全部','基金','股票','其他'].map(c=>`<button class="category-tab ${filter===c?'active':''}" data-category="${c}" role="tab" aria-selected="${filter===c}">${c}</button>`).join('')}</div><div class="holding-head"><span>基金</span><span>估算涨幅</span><span>今日涨幅</span><span>持有金额</span></div><div class="fund-list">${list.length?list.map(row).join(''):`<div class="empty-state">${filter}暂无持仓</div>`}</div></section>`}
function analysis(){title.textContent='分析';root.innerHTML=`<section class="analysis-page"><div class="analysis-columns"><section class="analysis-block"><p class="eyebrow">行业分布</p><h2>仓位</h2>${[['半导体','29%'],['贵金属','25%'],['海外科技','21%'],['宽基 / 其他','25%']].map(([n,v])=>`<div class="allocation"><div><span>${n}</span><b>${v}</b></div><i style="width:${v}"></i></div>`).join('')}</section><section class="analysis-block"><p class="eyebrow">仓位分析</p><h2>组合状态</h2><div class="analysis-row"><span>科技仓位</span><b class="negative">偏高</b><p>半导体与海外科技合计约 50%，需控制集中度。</p></div><div class="analysis-row"><span>防御仓位</span><b class="positive">稳定</b><p>贵金属提供波动缓冲，维持现有配置。</p></div></section></div><section class="observation"><p class="eyebrow">组合观察</p><h2>保持纪律，减少情绪化操作</h2><p>一年计划优先于单日节奏。沪深 300 继续定投，等待反弹后再优化结构。</p></section></section>`}
function render(v=view){view=v;document.querySelectorAll('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));({overview,portfolio,analysis}[v]||overview)()}
function detail(code){const f=acct().funds.find(x=>x.code===code);if(!f)return;const d=document.createElement('div');d.className='drawer-backdrop';d.innerHTML=`<aside class="detail-drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title"><button class="drawer-close" aria-label="关闭详情">×</button><div class="drawer-scroll"><p class="eyebrow">${f.category} · 基金详情</p><h2 id="detail-title">${esc(f.name)}</h2><p class="detail-code">${f.code}</p><div class="detail-values"><div><span>当前金额</span><b>${money(f.amount)}</b></div><div><span>持有收益</span><b class="${f.hold<0?'negative':'positive'}">${pct(f.hold)}</b></div><div><span>今日估算</span><b class="${f.today<0?'negative':'positive'}">${money(f.amount*f.today)}</b></div><div><span>今日涨幅</span><b class="${f.today<0?'negative':'positive'}">${pct(f.today)}</b></div></div><div class="detail-section"><p class="eyebrow">历史净值</p><h3>近1年走势</h3></div><div class="detail-section"><p class="eyebrow">前十大持仓</p><h3>主要持仓</h3><div class="holding-list">${f.holdings.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div></div><div class="detail-section"><p class="eyebrow">交易记录</p><h3>最近操作</h3><div class="transaction-list">${f.transactions.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b><em>${x[2]}</em></div>`).join('')}</div></div></div></aside>`;document.body.appendChild(d);requestAnimationFrame(()=>d.classList.add('visible'));d.addEventListener('click',e=>{if(e.target===d||e.target.closest('.drawer-close')){d.classList.remove('visible');setTimeout(()=>d.remove(),180)}})}
function addAccount(){const n=prompt('输入账户名称');if(n&&!accounts[n]){accounts[n]={name:n,funds:[]};render('overview')}}function addFund(){const n=prompt('输入基金名称');const c=prompt('输入六位基金代码');const a=Number(prompt('输入持有金额'));if(n&&/^[0-9]{6}$/.test(c)&&a){acct().funds.push({name:n,code:c,category:'基金',amount:a,today:0,hold:0,holdings:[],transactions:[]});render('portfolio')}}
document.querySelectorAll('.nav-tab').forEach(b=>b.addEventListener('click',()=>render(b.dataset.view)));root.addEventListener('click',e=>{const a=e.target.closest('[data-account]');if(a){active=a.dataset.account;render('portfolio')}const r=e.target.closest('[data-code]');if(r)detail(r.dataset.code);const c=e.target.closest('[data-category]');if(c){filter=c.dataset.category;render('portfolio')}if(e.target.closest('[data-action="add-account"]'))addAccount();if(e.target.closest('[data-action="add-fund"]'))addFund()});window.portfolioState={accounts,render,addAccount,getActive:()=>active,setActive:v=>{active=v}};render();
